### ISSUE TITLE
Issue with basic authentication

### ISSUE THREAD

**Issue by javsalgar** [kubeless/kubeless-ui#48]
When trying to access the Kubeless UI with basic authentication enabled, the UI works until you try to create a function.

<img width="794" alt="screen shot 2017-11-23 at 13 46 03" src="https://user-images.githubusercontent.com/1133777/33311385-f763bba2-d424-11e7-8a57-4f8083433e15.png">

<img width="530" alt="screen shot 2017-11-23 at 14 34 24" src="https://user-images.githubusercontent.com/1133777/33311440-1ef08f06-d425-11e7-976b-e28ffa23d172.png">

Steps to reproduce:
  
   - Create an ingress rule with basic authentication enabled to the Kubeless UI service
   - Create a function

**Comment by andresmgot** [comment]
@javsalgar can you post here the description of the Ingress object you have created? Also, which Ingress Controller are you using?

**Comment by javsalgar** [comment]
This is the ingress rule

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # type of authentication
    ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropiate context why the authentication is required
    ingress.kubernetes.io/auth-realm: "Authentication Required"
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
  labels:
    name: kubeapps
  name: kubeapps
  namespace: kubeapps
spec:
  rules:
  - host: null
    http:
      paths:
      - backend:
          serviceName: kubeapps-dashboard-ui
          servicePort: 80
        path: /
      - backend:
          serviceName: kubeapps-dashboard-api
          servicePort: 80
        path: /api/
      - backend:
          serviceName: kubeless-ui
          servicePort: 3000
        path: /kubeless
  tls: []

```

This is the ingress controller I'm using: 
https://github.com/kubernetes/ingress/blob/master/examples/deployment/nginx/kubeadm/nginx-ingress-controller.yaml
https://github.com/kubernetes/ingress/blob/master/examples/rbac/nginx/nginx-ingress-controller-rbac.yml
